# Generated by Django 5.2.8 on 2025-12-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='equipos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='formato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='pos1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='pos2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='pos3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='sedes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='ultimocampeon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
