# Generated by Django 5.2.8 on 2025-12-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReinas', '0002_torneo_categoria_torneo_equipos_torneo_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='fechaend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
