# Generated by Django 5.2.8 on 2025-12-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReinas', '0003_torneo_fechaend_alter_torneo_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
