# Generated by Django 6.0 on 2025-12-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReinas', '0004_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadora',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='jugadora',
            name='descripcion_breve',
            field=models.TextField(blank=True, max_length=200, verbose_name='Descripción breve'),
        ),
        migrations.AddField(
            model_name='jugadora',
            name='descripcion_completa',
            field=models.TextField(default='Información detallada de la jugadora.', verbose_name='Descripción completa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='posicion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
