# Generated by Django 6.0 on 2025-12-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReinas', '0005_remove_jugadora_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
